company: LOLOVIET
email: loloviet@gmai.com
phone: "0511.3538.266"
width_item: "100%"
en: "en"
vi: "vi"
username: 32
email: 64
password: 6
review: 8
description: 60
news_id: "1"
food_id: "2"
place_id: "3"
description_row: 3
content_row: 10
