company: LOLOVIET
email: loloviet@gmai.com
phone: "0511.3538.266"
width_item: "100%"
en: "en"
vi: "vi"
username: 32
email: 64
password: 6
review_page: 8
description: 60
description_row: 3
content_row: 10
review: "review"
tour: "tour"
parent_id_default: 0
avatar: "default-avatar.png"
zero: 0
two: 2
length:
  title: 3
  content: 5000
  description: 140
  name: 3
  phone: 10
paginate:
  categories: 10
  users: 15
  reviews: 10
  tours: 8
  bookings: 12
